project 'Phinger.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Phinger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Phinger

  target 'PhingerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhingerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
